version: '3.7'

services:
  zookeeper:
    container_name: 'zookeeper'
    image: wurstmeister/zookeeper
    networks:
      - mynetwork

  kafka:
      image: wurstmeister/kafka
      container_name: 'kafka'
      ports:
        - "9092:9092"
        - "9093:9093"
      networks:
        - mynetwork
      environment:
        JVM_OPTS: -Xmx1g -Xms1g -XX:MaxPermSize=1024m
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_CREATE_TOPICS: test_topic:1:1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092

  producer:
      build: ./Producer/
      ports:
        - "9000:9000"
      links:
        - kafka:kafka
      depends_on:
        - "kafka"
        - "zookeeper"
      environment:
          - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      networks:
        - mynetwork

networks:
  mynetwork:
      external: true