version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/container_data/zk-data:/var/lib/zookeeper/data
      - ./data/container_data/zk-txn-logs:/var/lib/zookeeper/log
    networks:
      - mynetwork

  kafka-1:
    build: .
    links:
      - zookeeper
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      EXTRA_ARGS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:39092,HOST://localhost:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

  postgres:
    build: ./postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=cs237
      - POSTGRES_USER=cs237
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=cs237uci@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Middleware@237
    ports:
      - '5488:5488'
    networks:
      - mynetwork

#  kafka-2:
#    build: .
#    links:
#      - zookeeper
#    ports:
#      - "19092:19092"
#      -  "7072:7072"
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      EXTRA_ARGS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7072:/usr/app/prom-jmx-agent-config.yml
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:49092,HOST://0.0.0.0:19092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:49092,HOST://localhost:19092
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      - mynetwork

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090/tcp"
    volumes:
      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka-1
      - producer
    networks:
      - mynetwork

  producer:
    container_name: producer
    build: ./Producer/
    ports:
      - "9000:9000"
    links:
      - kafka-1
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:39092
    networks:
      - mynetwork


  consumer:
    build: ./Consumer/
    ports:
      - "8000:8000"
    links:
      - kafka-1
      - producer
      - postgres
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:39092
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=notifydb
      - PGUSER=cs237
      - PGPASSWORD=cs237
    networks:
      - mynetwork
#
#  grafana:
#    image: grafana/grafana
#    container_name: 'grafana'
#    ports:
#      - '3000:3000'
#    depends_on:
#      - prometheus
#    networks:
#      - mynetwork


networks:
  mynetwork:
    external: true