version: '3.7'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    networks:
      - mynetwork
    ports:
      - '2181:2181'
    restart: on-failure

  kafka:
      image: wurstmeister/kafka:2.11-2.0.0
      container_name: kafka
      networks:
        - mynetwork
      links:
        - zookeeper
      environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      restart: on-failure

  producer:
      build: ./Producer/
      networks:
        - mynetwork
      ports:
        - "9092"
      links:
        - kafka
#      depends_on:
#        - "kafka"
#        - "zookeeper"
      environment:
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
networks:
  mynetwork:
      external: true