version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/container_data/zk-data:/var/lib/zookeeper/data
      - ./data/container_data/zk-txn-logs:/var/lib/zookeeper/log
    networks:
      - mynetwork

  kafka-1:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:39092,HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:39092,HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: '2'
    volumes:
      - ./data/container_data/kafka-1-data:/var/lib/kafka/data
    networks:
      - mynetwork

  kafka-2:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka-2
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:49092,HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:49092,HOST://localhost:19092
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: '2'
    volumes:
      - ./data/container_data/kafka-2-data:/var/lib/kafka/data
    networks:
      - mynetwork

  kafka-3:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka-3
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:59092,HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:59092,HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: '2'
    volumes:
      - ./data/container_data/kafka-3-data:/var/lib/kafka/data
    networks:
      - mynetwork

  producer:
    build: ./Producer/
    ports:
      - "9000"
    links:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:39092
    networks:
      - mynetwork

  consumer:
    build: ./Consumer/
    ports:
      - "8000"
    links:
      - kafka-1
      - kafka-2
      - kafka-3
      - producer
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:39092
    networks:
      - mynetwork

networks:
    mynetwork:
      external: true

