server:
  port: 8000

kafka:
  consumer:
    bootstrap: localhost:9092,localhost:9093,localhost:9094
    offset: earliest
    group1:
      id: group1
      topic: weather
      consumers: 3
    group2:
      id: group2
      topic: stock
      consumers: 3
    group3:
      id: group3
      topic: job
      consumers: 3

connection:
  timeout: 60000

logging:
  level:
    org:
      apache:
        http: DEBUG
        kafka: ERROR
      springframework:
        cloud:
          sleuth: INFO
    nodeValue: DEBUG


spring:
  mail:
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mail:
  smtp:
    debug: true


