global:
  scrape_interval: 10s

scrape_configs:
  - job_name: producer
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['producer:9000']

  - job_name: consumer-1
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ 'consumer-1:8000']
      labels:
        service: '1'
    - targets: ['consumer-2:8085']
      labels:
        service: '2'
    - targets: ['consumer-3:8090']
      labels:
        service: '3'

  - job_name: kafka1
    static_configs:
      - targets: ['kafka-1:7071']


