global:
  scrape_interval: 10s

scrape_configs:
  - job_name: producer
    metrics_path: '/actuator/prometheus'
    static_configs:
        - targets: ['producer:9000']

  - job_name: consumer
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: [ 'consumer:8000'   ]

  - job_name: kafka1
    static_configs:
      - targets: ['kafka:7071']


